### ISSUE TITLE
Stale connections may linger

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#160]
**Bug Description**

A node may erroneously consider itself connected to a peer for an extended period after the connection was dropped.  This disallows the node from reconnecting.

**Steps to Reproduce**

- Run a node on stagenet (or a small network) so that it will connect to all available nodes.
- Interrupt the network connection (e.g. disconnect from VPN)
- Shutdown the node
- Restart the node
- Reconnect the network connection

**Expected Result**

The node should be able to reconnect to its peers within a short amount of time.

**Actual Result**

Reconnecting to peers takes >10 minutes. The peers show as connected to the node, but the node does not show as connected to them on the network dashboard.

**Versions**
- Software Version 1.1.1

**Comment by abizjak** [comment]
This likely happens because the node does not get that the peer dropped the connection due to quirks of the VPN. The connection is finally dropped because of lack of activity after an interval.

This interval is currently hardcoded (in configuration.rs)
```
/// Maximum time (in ms) a node can hold an inactive connection to a peer.
pub const MAX_NORMAL_KEEP_ALIVE: u64 = 1_200_000;
```
(so 20min).

We should make this a configuration option and reduce the default to something more reasonable. We discussed now that 2min should probably be reasonable.

However we should make sure that this is a few times larger than the houskeeping interval so that the node has time to send and receive pings/pongs as well.
