### ISSUE TITLE
Closing the pool that has delegators doesn't redelegate delegators capital to the LPool

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-node#263]
**Bug Description**
Closing the pool that has delegators doesn't redelegate delegators capital to the LPool.

**Steps to Reproduce**
Start a baker and open pool for all.
Delegate with Delegator X to the opened pool.
After receiving first reward close the pool.

**Expected Result**
Delegator X capital should be moved to the  LPool.

**Actual Result**
Delegator X capital remains in the pool that was previously closed.

**Versions**
- Software Version: concordium-client_4.0.0-delegation-test-1

**Comment by mh-concordium** [comment]
Can I somehow see in what version of the node will this be/is fixed?

**Comment by abizjak** [comment]
Since delegation has been deployed to stagenet from a branch with unclear tagging and releases it is a bit more challenging.

Normally you should be able to see this from the changelog on the main branch.

In any case, this is not part of 4.0.6 version, so it will be in the next released version (next stagenet) which is currently expected Wednesday.
