### ISSUE TITLE
Node caching - LRU cache implementation & micro benchmarks.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#361]
Implement a LRU cache conforming the the cache interface and implement benchmarks to compare this solution to other FIFO cache solutions.

Currently the node-caching branch has a simple FIFO cache implemented. 
We should also have a LRU cache for benchmarks and to compare it with our FIFO cache. 

Supposedly the FIFOCache is much faster than the LRUCache because of the overhead in maintaining the LRUCache. But under different transaction activity patterns the LRU cache might yield better performance. 

Nonetheless this is something we need to investigate and thus we need to implement a LRUCache.

**Comment by rimbi** [comment]
A benchmark has been implemented which uses normal distribution to simulate the transactions and the accounts. With the assumption that a small portion of the accounts would produce most of the transactions on the network the following parameters chosen for the benchmark:
- cache size: 30K
- transaction count: 500K
- number of accounts: ~110K
- standard deviation: %10 (which means %68 of the transactions will be produced by 11K accounts)

Here is a result from the benchmark:

```console
benchmarking cache/test LRUCache  
time                 2.687 s    (2.654 s .. 2.701 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.709 s    (2.698 s .. 2.717 s)
std dev              11.58 ms   (6.241 ms .. 16.20 ms)
variance introduced by outliers: 19% (moderately inflated)
                                  
benchmarking cache/test FIFOCache 
time                 2.679 s    (2.654 s .. 2.700 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.669 s    (2.660 s .. 2.674 s)
std dev              8.645 ms   (482.2 μs .. 10.78 ms)
variance introduced by outliers: 19% (moderately inflated)
```

Here are the conclusions from the benchmark:
- LRUCache (using the `lrucache` lib) and the FIFOCache (our own basic FIFO implementation) performs similarly overall
- LRUCache performs slightly better in terms of cache misses
- FIFOCache has better execution performance but this gain is not that important when compared to the performance loose due to cache misses
- Overall, avoiding cache misses seems to be the thing we should focus on rather than the execution performance of the caches.

The action item:
- Integrate caching solutions into the node and perform the performance test in the real network environment.
