### ISSUE TITLE
Preliminary investigation of caching smart contracts & feature proposal

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#448]
Currently every module, instance etc. is being kept in memory. 
This will not be manageable as the number of smart contracts will grow on the chain. 

Before proposing a feature proposal for addressing this issue we will need to analyze how we want to introduce a caching mechanism for smart contracts.

**Comment by abizjak** [comment]
There are a few points to consider.
- the smart contract execution is designed so that it efficiently executes from essentially a byte array as the source (that's the "Artifact"). There is still a little bit of deserialization, but it should be negligible.
- I would really like to see whether just not caching the contract state at all is viable before any complex mechanism is attempted.

At least the following test scenarios should be considered
- a smart contract module that is reasonably large with an entrypoint that is a no-op (or as close to as possible). Invoke this as much as possible and see that block execution stays within the allotted time.
- A smart contract with a large tree as state. Invoke it with a parameter that causes the tree to be updated at "random" places. See that the costs are adequate to execute in the allotted time.
- A contract that traverses its own state as much as possible in a block.
- A contract that calls a list of other contracts as much as possible.
