### ISSUE TITLE
Promote usage of our status page

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-node#646]
It is sometimes vital for node runners, particularly bakers and finalizers, to get important messages from us. This is especially the case when they need to update their nodes to handle a new protocol version.

One of our primary channels is our status page (https://status.mainnet.concordium.software/), which allows users to subscribe to emails for specific components (fx the node). But it appears that not many people are aware of the status page.

We could change that in a couple of ways:

- [ ] Link to the status page from various pages in our developer documentation (it is already linked in some)
    - [ ]  This could include a small video/guide that shows how to subscribe to emails for all or some components
- [ ] Link to the status page and highly recommend its usage in the various node installers (i.e. directly in installer program text)

**Comment by abizjak** [comment]
What exactly is the actionable item for the node here? In practice I think most people either run the node using the docker image or the ubuntu one. We can't really put any notice in the docker one, it is just an image, there is no installer. We could put something in the startup script, but that is not something anybody will read.

For the ubuntu one we may include some messages at the end (but we also need to make it so installers work non-interactively). But I don't think this will be effective. There is a lot of output from the installer already that we cannot suppress, so this will be lost.

We can put something in the mac installer, but I don't think that matters for the network.

I don't know about Windows, but is the install on a server also non-interactive? How would this message be displayed to users there?

If the links in documentation to the status page are not already there then they should be made more prominent. 

It could make sense that instead of just downloading when clicking on a link, the download link goes to a page which displays this message, and also downloads the required node.

**Comment by Bargsteen** [comment]
Good points. You are right, at the impact of adding information to the manual mac and windows installers would be minimal for the actual network.

Danielle already made some improvements in the documentation with https://github.com/Concordium/concordium.github.io/pull/695

I like the idea of the custom download page you suggested. What do you think @dg-concordium?

**Comment by dg-concordium** [comment]
A custom download page is a good idea. I am in favor of repeating this information in as many places as possible.

**Comment by Bargsteen** [comment]
Ok, I've created an issue for a custom download page: https://github.com/Concordium/concordium.github.io/issues/697
So I'll close this issue.
