### ISSUE TITLE
Revise collectors collecting interval.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#912]
By default the collector is collecting every 5th second. 

When blocks arrive faster than the collecting interval the dashboard chain explorer is a bit laggy. 

We should revise our distributions such that they override the default value based on the `minimum block time` chain parameter.

**Comment by abizjak** [comment]
I don't think that's a good idea. minimum_block_time can be 0, and we don't want to spam the collector backend.

**Comment by abizjak** [comment]
Also in light of the fact that the chain explorer and the network dashboard itself is in maintenance/deprecation mode, I dont' think we want to be changing supporting services  because of it.

I think having a reasonable time for posting data to get an overview of the network is OK and I don't think we should be reducing that further just to support the chain explorer. There are other issues in the chain explorer, which also itself queries data from the backend only every so often.

**Comment by EmilLa1** [comment]
> I don't think that's a good idea. minimum_block_time can be 0, and we don't want to spam the collector backend.

Of course we should not blindly set it to the minimum block time i.e. in some unusual case where it's set to `0`. :)

My idea was just to set the the value according to the mainnet parameter. But maybe the 5s is ok for this.

**Comment by abizjak** [comment]
Rigth, but even 1s is excessive. We are creating a lot of data on the network, and load on our services.

And the refresh rate of the network dashboard is 2s I believe anyhow so that'd have to be changed if we go below it, ...

I really don't think this is the right direction. The chain explorer architecture as it is now is not good. We can do this on stagenet for internal testing, by setting the relevant configuration options for the collector service as is.
