### ISSUE TITLE
Node collector does not work when TLS is enabled on the node

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#989]
**Bug Description**

If the node is configured with TLS for its GRPC interface then the node collector is not able to collect data from it.

**Versions**
- Software Version: all

**Comment by EmilLa1** [comment]
Options I see for this.
1) Add localhost to SANs - however this comes with its own fair share of consequences and should be avoided. Moreover no CA's issue certificates with localhost so the certificate in that case must be a self-signed certificate which in turn would be very troublesome and annoying for "real" consumers of the grpc api. 
2) Add an extra http listener for the grpc api (with only the required endpoints exposed for the collector in order to function), and then the collector should always use that endpoint. 
3) Remove TLS configuration all together on the node and let node operators handle secure connections.
4) Collector does simply not work if tls is enabled on the node. I.e. stay as is. 
The collecting architecture is already flawed as is and there has been some talk about phasing the collector and regular dashboard out in favor of just ccdscan. 


I propose option 2 as that would integrate well into the **current** setup, but if we are to phase out the collector and dashboard anyhow anytime soon, I would vote for option 4.
Option 3 I see as the ideal solution, but it's ramifications are unclear as we do not know how many rely on tls in the node (or if operators are having a tls termination proxy in front of the node anyhow).
Option 1 is not really an option, just a thought.

Thoughts @td202 @abizjak ?

**Comment by abizjak** [comment]
1. That is not a good option.
2. This is hacky. Either we should just have http enabled for all endpoints or not, we should not hardcode some arbitrary set that happens to be used.
3. Is a no-go. TLS on the node is used and simplifies the setup quite a bit.
4. CCDScan uses the collector, so they are not exclusive.


We can do the following. Make the collector understand TLS (based on the schema) (currently it does not, it only supports http). Then we can document that if you enable TLS on the node you need to point the collector to the public URL of the node, and have that accessible.

Long term we will migrate away from the separate collector if we want to make it robust anyhow.

**Comment by EmilLa1** [comment]
Ok. We'll go with option 5)
If node is configured with TLS, then one has to configure the collector to use the url configured for the node, and hence it would have to go through proper dns resolving. 

I'll add this possibility to the collector and document it. Is there any external documentation that must be updated?
